name: 'Publish docker image'
description: 'This action publishes a docker image for valid tags on basis of a given architecture.'
inputs:
  arch:  # id of input
    description: 'Either "amd64" or "i386".'
    required: true
  docker_user:
    description: 'Username with push access to docker registry.'
    required: true
  docker_token:
    description: 'Token for user with push access to docker registry.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Prepare checking tag name
      uses: actions-ecosystem/action-regex-match@v2
      id: regex-match
      with:
        text: ${{ github.ref_name }}
        regex: '^v\d+\.\d+\.\d+$'

    - name: Check tag name
      id: check-tag-name
      run: |
        echo "Checking tag name: Did regex match? => [${{ steps.regex-match.outputs.match }}]";
        REMATCH="${{ steps.regex-match.outputs.match }}";
        REFNAME="${{ github.ref_name }}";
        [ -z "$REMATCH" ] && ${{ github.action_path }}/publish/error "ERROR: Tag '$REFNAME' has invalid format." 
      shell: bash

    - name: Login to docker hub
      id: login-to-docker-hub
      run: |
        echo "${{ inputs.docker_token }}" \
          | docker login -u "${{ inputs.docker_user }}" --password-stdin \
          || error "ERROR: Login to docker registry failed."
      shell: bash

    - name: Create 
      id: create
      run: |
        ./build.sh ${{ inputs.arch }} ${{ github.ref_name }} \
          || {
            echo "ERROR: Building docker image failed.";
            false;
          }
        true
      shell: bash

    - name: Tag and push 
      id: tag-and-push
      run: |
        IMAGE=$(cat /tmp/IMAGE);
        docker push $IMAGE \
          || {
            echo "ERROR: Pushing $IMAGE to docker registry failed.";
            false;
          }
        true
      shell: bash