name: 'Publish docker image'
description: 'This action publishes a docker image for valid tags on basis of a given architecture.'
inputs:
  arch:  # id of input
    description: 'Either "amd64" or "i386".'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions-ecosystem/action-regex-match@v2
      id: regex-match
      with:
        text: ${{ github.ref_name }}
        regex: '^v\d+\.\d+\.\d+\$'

    - name: Check tag name
      run: |
        [ -z "${{ steps.regex-match.outputs.match }}" ] && false
      shell: bash

    - name: Login to docker hub
      run: |
        echo "[${{ secrets.DOCKER_USER }}]";
        echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      shell: bash

    - name: Create 
      run: |
        ./build.sh ${{ inputs.arch }} ${{ github.ref_name }}
      shell: bash

    - name: Tag and push 
      run: |
        IMAGE=$(cat /tmp/IMAGE);
        docker push $IMAGE
      shell: bash